### ISSUE TITLE
Inconsistency in generation of technique administration files

### ISSUE THREAD

**Issue by SanWieb** [rabobank-cdc/DeTTECT#44]
Hi,

There is a small inconsistency at the generation of the technique administration files.

The command `python dettect.py ds -fd sample-data/data-sources-endpoints.yaml -y` will generate a administration file without a '-' before the `applicable_to` key. Like this:

```
  - technique_id: T1001.001
    technique_name: Junk Data
    detection:
      applicable_to:
      - all
      location:
      - ''
      comment: ''
      score_logbook:
      - date: 
        score: -1
        comment: ''
```

However in the example there is a '-' before `applicable_to`, the output of the DeTT&CT editor also contains the '-'.
A YAML exception (duplicated mapping key) occurs if you add another `applicable_to` block without '-'.
